apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: autorun
  namespace: autorun
  labels:
    app.kubernetes.io/name: autorun
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: autorun
