apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: autorun-data
  namespace: autorun
  labels:
    app.kubernetes.io/name: autorun
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard-rwo
  resources:
    requests:
      storage: 10Gi
