apiVersion: v1
kind: Secret
metadata:
  name: autorun-secret
  namespace: autorun
  labels:
    app.kubernetes.io/name: autorun
type: Opaque
stringData:
  AUTORUN_JWT_SECRET: "CHANGE-ME-to-a-64-char-random-string-before-deploying"
  SPRING_DATASOURCE_USERNAME: "autorun"
  SPRING_DATASOURCE_PASSWORD: "CHANGE-ME-db-password"
  AUTORUN_SMTP_HOST: ""
  AUTORUN_SMTP_PORT: "587"
  AUTORUN_SMTP_USERNAME: ""
  AUTORUN_SMTP_PASSWORD: ""
